from utils.csv_path_manager import get_tmp_csv

JOB_NAME = "fact_compras"

TMP_CSV = get_tmp_csv(JOB_NAME)

COLUMN_MAPPING = {
    'SEQAPRODET': 'IdFactCompras',
    'F_FECHA_EMISION_REQ': 'FechaRequerimiento',
    'F_FECHA_EMISION_OC': 'FechaOrdenCompra',
    'F_FECHA_ENTREGA': 'FechaEntregaItem',
    'F_FECHA_ALM': 'FechaIngresoAlmacen',
    'F_INGRESO_BANDEJA':'FechaIngresoBandeja',
    'F_SALIDA_BANDEJA':'FechaSalidaBandeja',
    'F_TIPO_FLUJO': 'IdDimFlujoCompra',
    'F_MONEDA': 'IdDimMoneda',
    'F_PRODUCTO': 'IdDimProducto',
    'F_PROVEEDOR': 'IdDimProveedor',
    'F_SITE': 'IdDimSite',
    'F_PGENERA': 'IdDimPersonalGenera',
    'F_PCOMPRADOR': 'IdDimPersonalComprador',
    'F_PBANDEJA': 'IdDimPersonalBandeja',
    'F_ESTADO_ITEM': 'IdDimEstadoItem',
    'F_ESTADO_OC': 'IdDimEstadoOC',
    'F_ESTADO_ALMACEN': 'IdDimEstadoAlmacen',
    'F_FPAGO': 'IdDimFormaPago',
    'F_TIPO_PROYECTO': 'IdDimTipoProyecto',
    'F_TIPO_REQ': 'IdDimTipoRequerimiento',
    'F_NRO_REQ': 'NroRequisicion',
    'F_NRO_OC': 'NroOrdenCompra',
    'F_CANT_PEDIDA': 'CantPedida',
    'F_CANT_ATENDIDA': 'CantAtendida',
    'F_CANT_DEVOLUCION': 'CantDevolucion',
    'F_PRECIO_COMPRA': 'PrecioCompra',
    'F_TIPO_CAMBIO': 'TipoCambio',
    'F_IGV': 'Igv'
}

SELECT_ORIGEN = """
    WITH NivelesRecursivosIngreso AS (  --82 066
        SELECT 
            CAST(MIN(fechaModi) AS DATE) AS FechaIngresoBandeja,
            MAX(usuario) AS cotizador,
            SEQAPRODET AS SEQAPRODET 
        FROM dbo.NIVELES
        WHERE Nivel = 3
        --AND SEQAPRODET = 323886
        AND usuario <> 6106
        GROUP BY SEQAPRODET
    ),
    NivelesRecursivosSalida AS(
        SELECT 
            CAST(MAX(N.fechaModi) AS DATE) AS FechaSalidaBandeja,
            N.SEQAPRODET AS SEQAPRODET 
        FROM dbo.NIVELES N
        WHERE Nivel >= 8  AND Estado = 23
        AND usuario <> 6106
        --AND SEQAPRODET = NivelesRecursivosIngreso.SEQAPRODET
        GROUP BY SEQAPRODET
    ),
	PrimerIngresoAlmacen AS (
		SELECT --INGRESO DE LA ORDEN DE COMPRA (TOTAL)
		ISNULL(DE10.seqaprodet_de10, DE10.SEQLIQ)  AS SEQLIQ ,
		MIN(DE10.FCHMOV) as FechaMinMov
		FROM de10
		INNER JOIN ca10 ON ca10.IdCabGuia = de10.IdCabGuia
		WHERE ca10.Y10004 = 'I' AND ca10.Y10075 = 1
		GROUP BY ISNULL(DE10.seqaprodet_de10, DE10.SEQLIQ)
	)
    SELECT
        COMAPROREQDET.SEQAPRODET,
        CAST(ALMPEDIDOCAB.FCHEDIT AS DATE) AS F_FECHA_EMISION_REQ,
        CAST(ISNULL(CA20.fecha_emi_oc, CA20.Y20006) AS DATE) AS F_FECHA_EMISION_OC,
        CAST(ISNULL(de20.FCHENTREGA, COMAPROREQDET.FCHENTREGA) AS DATE) AS F_FECHA_ENTREGA,
		CAST(PrimerIngresoAlmacen.FechaMinMov AS DATE) AS F_FECHA_ALM,
        CASE WHEN ISNULL(CA20.PROCESOO, COMAPROREQCAB.PROCESOR) IN (4, 18, 20) THEN CAST(NIngreso.FechaIngresoBandeja AS DATE)
        ELSE NULL END AS F_INGRESO_BANDEJA,
	    CASE WHEN ISNULL(CA20.PROCESOO, COMAPROREQCAB.PROCESOR) IN (4, 18, 20) THEN CAST(NSalida.FechaSalidaBandeja AS DATE)
		ELSE NULL END AS F_SALIDA_BANDEJA,
        CAST(ISNULL(CA20.PROCESOO, COMAPROREQCAB.PROCESOR) AS INT) AS F_TIPO_FLUJO,
        MONEDA.SEQMA00 AS F_MONEDA,
        MA04.SEQMA04 AS F_PRODUCTO,
        MA02.cod_prov AS F_PROVEEDOR,
        ALMPEDIDOCAB.SITEIDORIG AS F_SITE,
        ISNULL(ALMPEDIDOCAB.IDUSER, COMAPROREQCAB.idusu_genreq_cmc) AS F_PGENERA,
        ISNULL(COMAPROREQDET.idusuario_ctz_crd, 0) AS F_PCOMPRADOR,
        ISNULL(NIVELES.usuario,0)                 AS F_PBANDEJA,
        ISNULL(DE20.Estado, Niveles.Estado) AS F_ESTADO_ITEM,
        CA20.EstadoDoc AS F_ESTADO_OC,
        COMAPROREQDET.id_estado_aten_alm_crd AS F_ESTADO_ALMACEN,
        ISNULL(CA20.FORMAPAGO, ISNULL(COMAPROREQCAB.FORMAPAGO,0)) AS F_FPAGO,
        ISNULL(COMAPROREQDET.id_tipo_proyecto_ctz,0) AS F_TIPO_PROYECTO, 
        ISNULL(COMAPROREQCAB.id_origen_rq_ma00,0) AS F_TIPO_REQ,
        ALMPEDIDOCAB.NROREQUISION AS F_NRO_REQ,
        CA20.CORRESMG AS F_NRO_OC,
        CAST(ISNULL(DE20.Y20084, COMAPROREQDET.CANTPED) AS DECIMAL(18,2)) AS F_CANT_PEDIDA,
        CAST(ISNULL(DE20.RECIBIDO,0) AS DECIMAL(18,2)) AS F_CANT_ATENDIDA, 
        CAST(ISNULL(DE20.CantDevolucion,0) AS DECIMAL(18,2)) AS F_CANT_DEVOLUCION, 
        CAST(ISNULL(DE20.Y20082, ISNULL(COMAPROREQDET.IMPPCOMPRA,0)) AS DECIMAL(18,4)) AS F_PRECIO_COMPRA,
        CAST(MA50.Y50C66 AS DECIMAL(18,4)) AS F_TIPO_CAMBIO,
        CASE WHEN COALESCE(DE20.afectoigv, COMAPROREQDET.afectoigv, 1) = 0 THEN ISNULL(tipo_igv_d20,0) ELSE 0 END AS F_IGV
    FROM ALMPEDIDOCAB
    INNER JOIN COMAPROREQCAB ON COMAPROREQCAB.SEQPEDCAB = ALMPEDIDOCAB.SEQPEDCAB
    INNER JOIN COMAPROREQDET ON COMAPROREQDET.SEQAPROCAB = COMAPROREQCAB.SEQAPROCAB
    LEFT JOIN NivelesRecursivosSalida NSalida on NSalida.SEQAPRODET = COMAPROREQDET.SEQAPRODET
    LEFT JOIN NivelesRecursivosIngreso NIngreso on NIngreso.SEQAPRODET = COMAPROREQDET.SEQAPRODET
    LEFT JOIN ma50 ON CONVERT(VARCHAR(10), ISNULL(COMAPROREQCAB.FCHCOTIZA,COMAPROREQCAB.FCHEDIT), 110) = CONVERT(VARCHAR(10), MA50.Y50006, 110)
    INNER JOIN niveles on niveles.SEQAPRODET = COMAPROREQDET.SEQAPRODET and COMAPROREQDET.codnivel = niveles.codnivel
    LEFT JOIN DE20 ON DE20.SEQAPRODET = COMAPROREQDET.SEQAPRODET
    LEFT JOIN CA20 ON CA20.SEQAPROCAB = COMAPROREQCAB.SEQAPROCAB AND DE20.id_oc = CA20.Y20005
    LEFT JOIN MA04 ON MA04.Y04001 = ISNULL(DE20.Y20001, COMAPROREQDET.SEQPRODUCTO)
    LEFT JOIN MA02 ON MA02.Y02011 = ISNULL(CA20.Y20011, COMAPROREQDET.SEQPROVEEDOR)
    LEFT JOIN MA00 MONEDA on MONEDA.codigo = CAST(ISNULL(NULLIF(CA20.Y20055,''), ISNULL(COMAPROREQDET.MONEDA,0)) AS INT)
    AND MONEDA.clasif = '0002'
	LEFT JOIN PrimerIngresoAlmacen ON PrimerIngresoAlmacen.SEQLIQ = ISNULL(DE20.Y20005, COMAPROREQDET.SEQAPRODET) 
    WHERE ALMPEDIDOCAB.SERVREPUESTO = 'R'
    AND ALMPEDIDOCAB.FCHEDIT >= DATEFROMPARTS(YEAR(GETDATE()) - 1, 1, 1)
    AND ALMPEDIDOCAB.FCHEDIT <  DATEFROMPARTS(YEAR(GETDATE()) + 1, 1, 1)


    --AND CASE WHEN ISNULL(CA20.PROCESOO, COMAPROREQCAB.PROCESOR) IN (4, 18, 20) THEN CAST(NSalida.FechaSalidaBandeja AS DATE)
	--ELSE NULL END IS NOT NULL AND ISNULL(COMAPROREQDET.idusuario_ctz_crd, 0) = 0
"""

UPDATE_RECIBIDO_QUERY = """
    ; WITH RECIBIDO AS (
        SELECT --INGRESO DE LA ORDEN DE COMPRA (TOTAL)
        ISNULL(SUM(de10.Y10079),0) AS CNT_RECIBIDO,
        de10.SEQLIQ
        FROM de10
        INNER JOIN ca10 ON ca10.IdCabGuia = de10.IdCabGuia
        WHERE ca10.Y10004 = 'I' AND ca10.Y10075 = 1
        GROUP BY SEQLIQ
    ),
    DEVOLUCION AS (						
        SELECT  ----SALIDA POR DEVOLUCION
        ISNULL(SUM(de10.Y10079),0) AS CNT_DEVOLUCION,
        SEQLIQ
        FROM de10
        INNER JOIN ca10 ON ca10.IdCabGuia = de10.IdCabGuia
        WHERE ca10.Y10004 = 'S' AND ca10.Y10075 = 9
        GROUP BY SEQLIQ
    ),
    REPOSICION AS(

        SELECT  ----INGRESO X REPOSICION (B/SALIDA POR DEVOLUCION) 
        ISNULL(SUM(ext.Y10079),0) AS CNT_REPOSICION,
        de10.SEQLIQ
        FROM de10
        INNER JOIN de10 ext on ext.IdDetGuiaExt = de10.IdDetGuia
        INNER JOIN ca10 c1 ON c1.IdCabGuia = ext.IdCabGuia
        WHERE c1.Y10004 = 'I' 
        AND c1.Y10075 = 9 
        GROUP BY de10.SEQLIQ
    )
    --SELECT 
    --YEAR(ISNULL(CA20.fecha_emi_oc, CA20.Y20006)),
    --ABS(ISNULL(ISNULL(RECIBIDO.CNT_RECIBIDO, 0) - (ISNULL(DEVOLUCION.CNT_DEVOLUCION, 0) - ISNULL(REPOSICION.CNT_REPOSICION,0)), 0)),
    --RECIBIDO.CNT_RECIBIDO,
    --DEVOLUCION.CNT_DEVOLUCION,
    --REPOSICION.CNT_REPOSICION,
    --ca20.CORRESMG,de20.RECIBIDO,de20.*
    UPDATE DE20
    SET DE20.RECIBIDO = ABS(ISNULL(ISNULL(RECIBIDO.CNT_RECIBIDO, 0) - (ISNULL(DEVOLUCION.CNT_DEVOLUCION, 0) - ISNULL(REPOSICION.CNT_REPOSICION,0)), 0))
    FROM CA20
    INNER JOIN DE20 ON DE20.id_oc = CA20.Y20005
    LEFT JOIN RECIBIDO ON RECIBIDO.SEQLIQ = DE20.Y20005
    LEFT JOIN DEVOLUCION ON DEVOLUCION.SEQLIQ = DE20.Y20005
    LEFT JOIN REPOSICION ON REPOSICION.SEQLIQ = DE20.Y20005
    WHERE DE20.RECIBIDO > DE20.Y20084
    AND CA20.Y20004 = 'P'
    AND DE20.RECIBIDO > DE20.Y20084
    AND YEAR(ISNULL(CA20.fecha_emi_oc, CA20.Y20006)) >= 2024;
    ---AND ca20.PROCESOO IN (4,18,20);
"""

TABLA_DESTINO = "FactCompras"